 export const img1="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc7oA_lJcdpHZsQ8HdZSNdk5rF1X3HefwMu5SXbFC0iK6Qk_eZ5qk6hyWAxzBdGkz_M7I&usqp=CAU"
 export const img2="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMUqPsWz_dcHK1R8XTP-IX6NHYUW4GYQ_cYw&s"
 export const img3="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXTPuiJmJPHb-4ES2ESNMTU61N2Y1-vANe2w&s"
 export const img4="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlRYwS5A0rCCfblZi-Tt2sj8U7LzDZ1u6x1g&s"
 export const img5="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA5Bw2LZRc0j40ByHvOJt1N0oms6_qgQsaKQ&s"